# Generated by Django 5.2.3 on 2025-07-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseStationInfo",
            fields=[
                (
                    "bts_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="基站ID",
                    ),
                ),
                (
                    "bts_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="基站名称"
                    ),
                ),
                (
                    "frequency_band",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="频段"
                    ),
                ),
                (
                    "coverage_distance",
                    models.FloatField(
                        blank=True,
                        help_text="单位：公里",
                        null=True,
                        verbose_name="覆盖距离(公里)",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="地区号"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="站点经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="站点纬度"),
                ),
            ],
            options={
                "verbose_name": "基站信息",
                "verbose_name_plural": "基站信息",
            },
        ),
        migrations.CreateModel(
            name="ShipInfo",
            fields=[
                (
                    "mmsi",
                    models.CharField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="MMSI号码",
                    ),
                ),
                ("ship_name", models.CharField(max_length=100, verbose_name="船名")),
                (
                    "call_sign",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="呼号"
                    ),
                ),
                (
                    "ship_owner",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="船东"
                    ),
                ),
            ],
            options={
                "verbose_name": "船舶信息",
                "verbose_name_plural": "船舶信息",
            },
        ),
        migrations.CreateModel(
            name="TerminalInfo",
            fields=[
                (
                    "sn",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="SN码",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "port_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="端口号"
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terminal_management.shipinfo",
                        to_field="call_sign",
                        verbose_name="所属船舶呼号",
                    ),
                ),
            ],
            options={
                "verbose_name": "端站信息",
                "verbose_name_plural": "端站信息",
            },
        ),
        migrations.CreateModel(
            name="TerminalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField(verbose_name="设备类型号")),
                (
                    "sn",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="设备序列号"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(db_index=True, verbose_name="上报日期"),
                ),
                ("report_time", models.TimeField(verbose_name="上报时间")),
                ("op", models.IntegerField(verbose_name="操作类型")),
                ("op_sub", models.IntegerField(verbose_name="操作子类")),
                (
                    "long",
                    models.FloatField(blank=True, null=True, verbose_name="端站经度"),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="端站纬度"),
                ),
                (
                    "theory_yaw",
                    models.FloatField(blank=True, null=True, verbose_name="理论方位角"),
                ),
                (
                    "yaw",
                    models.FloatField(blank=True, null=True, verbose_name="当前方位角"),
                ),
                (
                    "pitch",
                    models.FloatField(blank=True, null=True, verbose_name="当前俯仰角"),
                ),
                (
                    "roll",
                    models.FloatField(blank=True, null=True, verbose_name="当前横滚角"),
                ),
                (
                    "yao_limit_state",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="方位限位"
                    ),
                ),
                (
                    "temp",
                    models.FloatField(blank=True, null=True, verbose_name="温度(°C)"),
                ),
                (
                    "humi",
                    models.FloatField(blank=True, null=True, verbose_name="湿度(%)"),
                ),
                (
                    "bts_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="基站名"
                    ),
                ),
                (
                    "bts_long",
                    models.FloatField(blank=True, null=True, verbose_name="基站经度"),
                ),
                (
                    "bts_lat",
                    models.FloatField(blank=True, null=True, verbose_name="基站纬度"),
                ),
                (
                    "bts_freq",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="基站频段"
                    ),
                ),
                (
                    "bts_r",
                    models.FloatField(
                        blank=True, null=True, verbose_name="基站覆盖半径(公里)"
                    ),
                ),
                (
                    "upstream_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="上行速率(Mbps)"
                    ),
                ),
                (
                    "downstream_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="下行速率(Mbps)"
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="通信制式"
                    ),
                ),
                (
                    "plmn",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="运营商PLMN"
                    ),
                ),
                (
                    "cellid",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="服务小区CellID",
                    ),
                ),
                (
                    "pci",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="服务小区PCI"
                    ),
                ),
                (
                    "rsrp",
                    models.FloatField(
                        blank=True, null=True, verbose_name="RSRP(信号接收功率)"
                    ),
                ),
                (
                    "sinr",
                    models.FloatField(
                        blank=True, null=True, verbose_name="SINR(信噪比)"
                    ),
                ),
                (
                    "rssi",
                    models.FloatField(
                        blank=True, null=True, verbose_name="RSSI(信号强度指示)"
                    ),
                ),
            ],
            options={
                "verbose_name": "端站上报信息",
                "verbose_name_plural": "端站上报信息",
                "indexes": [
                    models.Index(
                        fields=["sn", "report_date"], name="terminal_ma_sn_ff09dd_idx"
                    )
                ],
                "unique_together": {("type", "sn", "report_date", "report_time")},
            },
        ),
    ]
