# Generated by Django 5.2.3 on 2025-07-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminalinfo",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="terminal_management.shipinfo",
                verbose_name="所属船舶",
            ),
        ),
    ]
