# Generated by Django 5.2.3 on 2025-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0002_alter_terminalinfo_ship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basestationinfo",
            name="frequency_band",
        ),
    ]
