# Generated by Django 5.2.3 on 2025-08-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0003_remove_basestationinfo_frequency_band"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terminalreport",
            name="bts_freq",
        ),
        migrations.AddField(
            model_name="terminalreport",
            name="bts_group_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="基站分区号"
            ),
        ),
        migrations.AddField(
            model_name="terminalreport",
            name="bts_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="基站编号"
            ),
        ),
        migrations.AddField(
            model_name="terminalreport",
            name="dgps_err",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="DGPS差分状态"
            ),
        ),
        migrations.AddField(
            model_name="terminalreport",
            name="dgps_start",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="DGPS启动状态"
            ),
        ),
    ]
