# Generated by Django 5.2.3 on 2025-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0004_remove_terminalreport_bts_freq_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terminalreport",
            name="dgps_err",
        ),
        migrations.RemoveField(
            model_name="terminalreport",
            name="dgps_start",
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="bts_group_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="基站分区号"),
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="bts_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="基站编号"),
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="op",
            field=models.CharField(max_length=20, verbose_name="操作类型"),
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="op_sub",
            field=models.CharField(max_length=20, verbose_name="操作子类"),
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="type",
            field=models.CharField(max_length=100, verbose_name="设备类型名"),
        ),
        migrations.AlterField(
            model_name="terminalreport",
            name="yao_limit_state",
            field=models.FloatField(blank=True, null=True, verbose_name="方位限位"),
        ),
    ]
