# Generated by Django 5.2.3 on 2025-08-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0005_remove_terminalreport_dgps_err_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminalreport",
            name="system_stat",
            field=models.IntegerField(blank=True, null=True, verbose_name="系统状态"),
        ),
        migrations.AddField(
            model_name="terminalreport",
            name="wireless_network_stat",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="无线网络状态"
            ),
        ),
    ]
