# Generated by Django 5.2.6 on 2025-11-13 10:44

from django.db import migrations

# --- 详细定义我们将要执行的 SQL 语句 ---

# SQL 1: 添加一个“存储型(STORED)”生成列
# 
# !!! 修复点 !!!
# 我们将 STR_TO_DATE 的格式从 '%Y-%m-%d %H:%i:%s'
# 更改为 '%Y-%m-%d %H:%i:%s.%f'
# 
# 增加了 '%f' 来正确处理 'report_time' 字段中存储的微秒 (例如 .000000)
#
ADD_STORED_COLUMN_SQL = """
ALTER TABLE `terminal_management_terminalreport`
ADD COLUMN `report_datetime_generated` DATETIME(6) AS 
(STR_TO_DATE(CONCAT(report_date, ' ', report_time), '%Y-%m-%d %H:%i:%s.%f')) STORED;
"""
# 注意：我还将 DATETIME 更新为 DATETIME(6) 来保留微秒精度，这对于索引和查询更准确。

# SQL 2: 在新列和 'sn' 上创建复合索引
ADD_INDEX_SQL = """
CREATE INDEX `report_sn_datetime_gen_idx` 
ON `terminal_management_terminalreport` (`sn`, `report_datetime_generated`);
"""

# --- 回滚 SQL (如果迁移失败或你需要撤销迁移时执行) ---

# SQL 3: 删除索引 (与 SQL 2 对应)
DROP_INDEX_SQL = """
DROP INDEX `report_sn_datetime_gen_idx` ON `terminal_management_terminalreport`;
"""

# SQL 4: 删除列 (与 SQL 1 对应)
DROP_COLUMN_SQL = """
ALTER TABLE `terminal_management_terminalreport` DROP COLUMN `report_datetime_generated`;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_management", "0006_terminalreport_system_stat_and_more"),
    ]

    operations = [
        # 步骤 1: 执行 SQL 1 (添加列)
        migrations.RunSQL(
            sql=ADD_STORED_COLUMN_SQL,
            reverse_sql=DROP_COLUMN_SQL,
        ),
        
        # 步骤 2: 执行 SQL 2 (添加索引)
        migrations.RunSQL(
            sql=ADD_INDEX_SQL,
            reverse_sql=DROP_INDEX_SQL,
        ),
    ]